"""init

Revision ID: 47c208b645ca
Revises: 
Create Date: 2026-01-03 17:41:22.700539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47c208b645ca'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ownerships', sa.Column('tx_status', sa.Enum('pending', 'confirmed', 'failed', name='txstatus'), nullable=False))
    op.add_column('properties', sa.Column('token_id', sa.Integer(), nullable=True))
    op.add_column('properties', sa.Column('contract_address', sa.String(length=42), nullable=True))
    op.add_column('properties', sa.Column('mint_tx_hash', sa.String(length=66), nullable=True))
    op.add_column('properties', sa.Column('is_onchain', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('wallet_address', sa.String(length=42), nullable=False))
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_column('users', 'wallet_address')
    op.drop_column('properties', 'is_onchain')
    op.drop_column('properties', 'mint_tx_hash')
    op.drop_column('properties', 'contract_address')
    op.drop_column('properties', 'token_id')
    op.drop_column('ownerships', 'tx_status')
    # ### end Alembic commands ###
